# Generated by Django 6.0.1 on 2026-01-19 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField(default=datetime.date.today)),
                ('time_slot', models.CharField(choices=[('09:00', '9:00 AM'), ('12:00', '12:00 PM'), ('15:00', '3:00 PM'), ('18:00', '6:00 PM'), ('21:00', '9:00 PM')], default='12:00', max_length=5)),
                ('delivery_status', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('progress', 'In Progress')], default='progress', max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('delivery_assigned_to', models.CharField(choices=[('none', 'None'), ('dc1', 'DC1'), ('dc2', 'DC2'), ('dc3', 'DC3')], default='none', max_length=4)),
            ],
        ),
    ]
